# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
notifications:
  email:
    on_success: pschmidte@gmail.com
    on_failure: pschmidte@gmail.com
